version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management  # This includes the management plugin
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # Web UI for RabbitMQ Management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always